version: '3'
# 定义锚点卷配置 
x-shared-volumes: &shared-volumes 
  volumes:
    - ./gpt_server:/gpt_server/gpt_server # 将最新代码直接映射到容器中，以运行最新的代码
    - /home/dev/model/:/home/dev/model/ # 映射模型路径
services:
  gpt_server:
    # 构建
    # build:
    #   context: .
    #   dockerfile: Dockerfile.copy
    image: docker.1ms.run/506610466/gpt_server:latest
    container_name: gpt_server
    shm_size: '4g' # 设置共享内存为4GB 
    restart: always
    # network_mode: host
    ports:
      - 8082:8082
    environment:
      - TZ:Asia/Shanghai  # 设置中国时区
    <<: *shared-volumes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: [ '0', '1', '2', '3' ]
              count: all
              # count: 2  # 两种方式
              capabilities: [ gpu ]
    command: python gpt_server/serving/main.py
