serve_args:
  # openai 服务的 host 和 port
  enable: true
  host: 0.0.0.0
  port: 8082
  controller_address: http://localhost:21001 # 控制器的ip地址
  api_keys: null # api_keys: 111,222  # 用来设置 openai 密钥
controller_args:
  # 控制器的配置参数
  enable: true
  host: 0.0.0.0
  port: 21001
  dispatch_method: shortest_queue # lottery、shortest_queue # 现有两种请求分发策略，随机（lottery） 和 最短队列（shortest_queue），最短队列方法更推荐。

model_worker_args:
  # 模型的配置参数，这里port 不能设置，程序自动分配，并注册到 控制器中。
  # model worker 的配置参数
  host: 0.0.0.0
  controller_address: http://localhost:21001
models:
- minicpmv:
    alias: null
    enable: false
    model_config:
      model_name_or_path: /home/dev/model/OpenBMB/MiniCPM-V-2_6/
      enable_prefix_caching: false
    model_type: minicpmv
    work_mode: lmdeploy-turbomind
    device: gpu
    workers:
    - gpus:
      - 3
- internvl2:
    alias: null
    enable: false
    model_config:
      model_name_or_path: /home/dev/model/OpenGVLab/InternVL2-40B-AWQ/
      enable_prefix_caching: false
    model_type: internvl2
    work_mode: lmdeploy-turbomind
    device: gpu
    workers:
    - gpus:
      - 3
- chatglm4:
    alias: chatglm3
    enable: true
    model_config:
      model_name_or_path: /home/dev/model/ZhipuAI/glm-4-9b-chat
      enable_prefix_caching: false
    model_type: chatglm
    work_mode: vllm
    device: gpu
    workers:
    - gpus:
      - 3

- qwen-32b:
    alias: qwen,gpt-4,gpt-4o,gpt-3.5-turbo,gpt-3.5-turbo-16k
    enable: true
    model_config:
      model_name_or_path: /home/dev/model/Qwen/Qwen2___5-32B-Instruct-AWQ/
      enable_prefix_caching: true
      dtype: auto
      max_model_len: 65536
      kv_cache_quant_policy: 8
    model_type: qwen
    work_mode: lmdeploy-turbomind
    device: gpu
    workers:
    - gpus:
      - 0
      - 1
    # - gpus:
    #   - 3
    #   - 2
- piccolo-base-zh:
    alias: null
    enable: true
    model_config:
      model_name_or_path: /home/dev/model/assets/embeddings/sensenova/piccolo-base-zh/
    model_type: embedding_infinity
    work_mode: hf
    device: gpu
    workers:
    - gpus:
      - 2
- injection:
    alias: null
    enable: true
    model_config:
      model_name_or_path: /home/dev/model/protectai/deberta-v3-base-prompt-injection-v2
    model_type: embedding_infinity
    work_mode: hf
    device: gpu
    workers:
    - gpus:
      - 2
- bge-reranker-base:
    alias: null
    enable: true
    model_config:
      model_name_or_path: /home/dev/model/Xorbits/bge-reranker-base/
    model_type: embedding_infinity
    work_mode: hf
    device: gpu
    workers:
    - gpus:
      - 2
- MiniCPM-Embedding:
    alias: null
    enable: false
    model_config:
      model_name_or_path: /home/dev/model/openbmb/MiniCPM-Embedding
    model_type: embedding_infinity
    work_mode: hf
    device: gpu
    workers:
    - gpus:
      - 2
